"""GENERATED by tools/gen_tokens.py from design/tokens.json — do not edit.

The two pieces of the visual base that BOTH render paths share, carried over to
the Python side so nothing is hand-copied:

  TOKENS_CSS   — the `:root` block, from design/tokens.json
  ELEMENTS_CSS — the element base, from frontend/src/styles/base-elements.css

The React path gets the same two via frontend/src/styles/base.css. @font-face is
deliberately absent from both: that is the one rule the paths must not share
(font-display block vs swap). See docs/design-system.md.
"""

# Generated from design/tokens.json.
TOKENS_CSS = """
  :root{
    /* color */
    --bg:#f5f6f9;   /* page background */
    --panel:#ffffff;   /* card / panel surface */
    --panel2:#eef1f5;   /* inset surface — code, table head, chips */
    --line:#eceef2;   /* hairline divider */
    --line2:#e2e6ec;   /* control border */
    --ink:#101828;   /* primary text */
    --ink2:#475467;   /* secondary text */
    --mut:#8a93a3;   /* muted text — labels, meta */
    --acc:#5b5bf0;   /* primary action */
    --acc-ink:#4a45d6;   /* link / pressed action */
    --on-solid:#ffffff;   /* text/icons on any saturated fill (--acc, --good, --bad) */
    --good:#0f9d58;   /* success */
    --good-bg:#e7f6ee;   /* success surface */
    --warn:#b7791f;   /* warning */
    --bad:#e5484d;   /* danger */
    --bad-bg:#fdeaea;   /* danger surface */
    --bad-soft:#fff5f5;   /* the failed-to-load card's fill (set from TS) */
    --acc-soft:#edecfe;   /* accent surface — chips, selected rows */
    --acc-bg:#eeeefe;   /* accent surface, identity page's one-off shade */
    --warn-bg:#fbf3e2;   /* warning surface, identity page */
    --dup:#5b5bf0;   /* duplicate-identity marker (same hue as --acc) */
    --star:#f5a623;   /* rating star, calibrate page */
    --violet:#8b5cf6;   /* computed-metric accent */
    --violet-bg:#f0ebfe;   /* computed-metric surface */
    --code-bg:#0d1117;   /* code block fill */
    --code-fg:#c9d1d9;   /* code block text */
    --chg-design:#8250df;   /* changelog 'design' category (was a second --app) */
    --chg-design-bg:rgba(130,80,223,.14);   /* its pill fill */
    --swatch-empty:#888888;   /* a work-type with no colour set yet */
    --company-empty:#8b949e;   /* a company with no colour pinned or derived */
    /* chart */
    --plat:#5b5bf0;   /* platform effort */
    --app:#8b5cf6;   /* application effort */
    --c-commit:#5b5bf0;
    --c-loc:#8b5cf6;
    --c-pr:#2f80ed;
    --c-spec:#f59e0b;
    --c-bug:#ef4444;
    --c-epic:#8b5cf6;
    --c-story:#10b981;
    --c-feature:#10b981;
    --c-people:#06b6d4;
    --c-other:#9aa3b2;   /* uncategorised / 'Other' */
    /* category */
    --cat-bug:#ef4444;
    --cat-feature:#10b981;
    --cat-task:#8b5cf6;
    --cat-epic:#5b5bf0;
    --cat-spec:#f59e0b;
    --cat-docs:#06b6d4;
    --cat-test:#2f80ed;
    --cat-other:#9aa3b2;
    /* status */
    --pill-good-bg:#dafbe1;   /* org member, verified identity */
    --pill-good-fg:#116329;
    --pill-attn-bg:#fff8c5;   /* external, name-matched identity */
    --pill-attn-fg:#7d4e00;
    --pill-bad-bg:#ffebe9;   /* unresolved identity */
    --pill-bad-fg:#cf222e;
    --exact-bg:#eafff0;   /* 'exact' evidence badge */
    --exact-fg:#1a7f37;
    --heur-bg:#fff8e6;   /* 'heuristic' evidence badge */
    --heur-fg:#9a6700;
    --exp-bg:#f59e0b22;   /* 'experimental' badge — amber at 13% / 33% */
    --exp-line:#f59e0b55;
    --exp-fg:#c77700;
    --good-line:#a0d8b0;   /* healthy card / status border */
    --warn-line:#e8d8a0;   /* at-risk card / status border */
    --bad-line:#e6a0a0;   /* failed status border */
    --run-line:#a9c7ea;   /* job in progress */
    --run-bg:#f0f6fc;
    --tag-ext-line:#d4b75c;   /* 'external' tag border */
    --tag-legacy-line:#c4a7e7;   /* 'legacy' tag border */
    --period-line:#aacbf0;   /* active period tag border */
    --row-hover:#f7f8fc;   /* table row hover */
    --row-alt:#f4f5f7;   /* grouped table, even first cell */
    --row-alt-hover:#e9f2fc;
    --tooltip-bg:#1f2328;   /* tooltip and log surfaces — dark, so text on it is --on-solid */
    --chat-tool-bg:#f6f8fa;   /* tool-call block in the chat log */
    --option-fg:#111111;   /* native <option> text, which ignores most inherited colour */
    /* radius */
    --r:16px;   /* card */
    --r-sm:12px;   /* inner card, control */
    /* shadow */
    --sh:0 1px 2px rgba(16,24,40,.04),0 1px 3px rgba(16,24,40,.06);   /* resting card / button */
    --sh-lift:0 10px 30px rgba(16,24,40,.10);   /* hover / floating */
  }
"""

# Copied verbatim from frontend/src/styles/base-elements.css.
ELEMENTS_CSS = """
  /* The element base — html/body reset, headings, buttons, form controls, code.
     THE one copy. Both render paths get exactly this text:
       - the React path imports it from base.css (Vite inlines it)
       - the Python path gets it as tokens.ELEMENTS_CSS, which tools/gen_tokens.py
         copies out of this file into backend/tokens.py
     It used to live twice, hand-copied, and the copies had to be reconciled by eye.
     Do not add @font-face here: that is the ONE rule the two paths must NOT share
     (block on React, swap on Python — see base.css for why). */

    /* Always reserve the vertical scrollbar so navigating between short pages (no
       scrollbar) and tall ones (scrollbar) doesn't shift the layout — the sidebar
       was visibly "jumping" horizontally by the scrollbar width on each route
       change (each React route is a full page load). No-op where scrollbars are
       overlay (macOS trackpad) or where the page already scrolls. */
    html{overflow-y:scroll}
    /* margin:0 belongs here, not per page: most pages reset it in their own CSS but
       /identity and /views never did (their legacy templates didn't either), so the
       browser's default 8px shifted the WHOLE page — sidebar included — right and
       down on those routes. Shared = both the React shell and the legacy pages get
       the reset, so pixel-parity holds while the routes stop disagreeing. */
    body{margin:0;background:var(--bg);color:var(--ink);
      font-family:'Jakarta','Inter',-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
      -webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}
    h1,h2,h3{letter-spacing:-.02em}
    h1{font-weight:800} h2,h3{font-weight:700}
    .num{font-variant-numeric:tabular-nums;letter-spacing:-.02em}
    a{color:var(--acc-ink)}
    /* Buttons — pill-ish, Jakarta, indigo primary. Matches the report chrome. */
    button,.btn,a.btn,input[type=submit]{border:1px solid var(--line2);background:var(--panel);
      color:var(--ink);border-radius:10px;padding:8px 14px;font:600 13.5px/1.4 inherit;cursor:pointer;
      box-shadow:var(--sh);transition:border-color .12s,background .12s,box-shadow .12s}
    button:hover,.btn:hover,a.btn:hover{border-color:var(--line2);box-shadow:var(--sh-lift)}
    button.primary,.btn.primary,a.btn.primary,input[type=submit]{background:var(--acc);
      border-color:var(--acc);color:var(--on-solid);box-shadow:0 4px 12px rgba(91,91,240,.28)}
    button.primary:hover,.btn.primary:hover{background:var(--acc-ink);border-color:var(--acc-ink)}
    button:disabled,.btn:disabled{opacity:.5;cursor:default;box-shadow:none}
    /* Form controls */
    input,select,textarea{border:1px solid var(--line2);border-radius:10px;padding:8px 11px;
      font:inherit;font-size:14px;background:var(--panel);color:var(--ink)}
    input:focus,select:focus,textarea:focus{outline:none;border-color:var(--acc);
      box-shadow:0 0 0 3px rgba(91,91,240,.14)}
    code{background:var(--panel2);padding:1px 5px;border-radius:6px;font-size:12.5px}
"""
