"""GENERATED by tools/gen_tokens.py from design/tokens.json — do not edit.

The two pieces of the visual base that BOTH render paths share, carried over to
the Python side so nothing is hand-copied:

  TOKENS_CSS   — the `:root` block, from design/tokens.json
  ELEMENTS_CSS — the element base, from frontend/src/styles/base-elements.css

The React path gets the same two via frontend/src/styles/base.css. @font-face is
deliberately absent from both: that is the one rule the paths must not share
(font-display block vs swap). See docs/design-system.md.
"""

# Generated from design/tokens.json.
TOKENS_CSS = """
  :root{
    /* color */
    --bg:#f5f6f9;   /* page background */
    --panel:#ffffff;   /* card / panel surface */
    --panel2:#eef1f5;   /* inset surface — code, table head, chips */
    --line:#eceef2;   /* hairline divider */
    --line2:#e2e6ec;   /* control border */
    --ink:#101828;   /* primary text */
    --ink2:#475467;   /* secondary text */
    --mut:#656e80;   /* muted text — labels, meta. Darkened 2026-08-03 from #8a93a3, which was 2.73:1 on --panel2 — below AA even for large text — across 223 uses. */
    --acc:#5b5bf0;   /* primary action */
    --acc-ink:#4a45d6;   /* link / pressed action */
    --on-solid:#ffffff;   /* text/icons on any saturated fill (--acc, --good, --bad) */
    --good:#0c7f47;   /* success. Darkened 2026-08-03 from #0f9d58 (3.14:1 on --good-bg). */
    --good-bg:#e7f6ee;   /* success surface */
    --warn:#a26b1b;   /* warning. Darkened 2026-08-03 from #b7791f (3.64:1 on --panel). */
    --bad:#d41e24;   /* danger. Darkened 2026-08-03 from #e5484d (3.38:1 on --bad-bg). */
    --bad-bg:#fdeaea;   /* danger surface */
    --bad-soft:#fff5f5;   /* the failed-to-load card's fill (set from TS) */
    --acc-soft:#edecfe;   /* accent surface — chips, selected rows */
    --acc-bg:#eeeefe;   /* accent surface, identity page's one-off shade */
    --warn-bg:#fbf3e2;   /* warning surface, identity page */
    --dup:#5b5bf0;   /* duplicate-identity marker (same hue as --acc) */
    --star:#f5a623;   /* rating star, calibrate page */
    --violet:#8b5cf6;   /* computed-metric accent */
    --violet-bg:#f0ebfe;   /* computed-metric surface */
    --code-bg:#0d1117;   /* code block fill */
    --code-fg:#c9d1d9;   /* code block text */
    --chg-design:#8250df;   /* changelog 'design' category (was a second --app) */
    --chg-design-bg:rgba(130,80,223,.14);   /* its pill fill */
    --swatch-empty:#888888;   /* a work-type with no colour set yet */
    --company-empty:#8b949e;   /* a company with no colour pinned or derived */
    /* chart */
    --plat:#5b5bf0;   /* platform effort */
    --app:#8b5cf6;   /* application effort */
    --c-commit:#5b5bf0;
    --c-loc:#8b5cf6;
    --c-pr:#2f80ed;
    --c-spec:#f59e0b;
    --c-bug:#ef4444;
    --c-epic:#8b5cf6;
    --c-story:#10b981;
    --c-feature:#10b981;
    --c-people:#06b6d4;
    --c-other:#9aa3b2;   /* uncategorised / 'Other' */
    /* category */
    --cat-bug:#ef4444;
    --cat-feature:#10b981;
    --cat-task:#8b5cf6;
    --cat-epic:#5b5bf0;
    --cat-spec:#f59e0b;
    --cat-docs:#06b6d4;
    --cat-test:#2f80ed;
    --cat-other:#9aa3b2;
    /* status */
    --pill-good-bg:#dafbe1;   /* org member, verified identity */
    --pill-good-fg:#116329;
    --pill-attn-bg:#fff8c5;   /* external, name-matched identity */
    --pill-attn-fg:#7d4e00;
    --pill-bad-bg:#ffebe9;   /* unresolved identity */
    --pill-bad-fg:#cf222e;
    --exact-bg:#eafff0;   /* 'exact' evidence badge */
    --exact-fg:#1a7f37;
    --heur-bg:#fff8e6;   /* 'heuristic' evidence badge */
    --heur-fg:#9a6700;
    --exp-bg:#f59e0b22;   /* 'experimental' badge — amber at 13% / 33% */
    --exp-line:#f59e0b55;
    --exp-fg:#9a5c00;   /* Darkened 2026-08-03 from #c77700, which was 3.13:1 on the badge fill. --exp-bg is amber at 13% alpha, compositing to #fef2de over a card, so the fill is far lighter than its hex suggests. */
    --good-line:#a0d8b0;   /* healthy card / status border */
    --warn-line:#e8d8a0;   /* at-risk card / status border */
    --bad-line:#e6a0a0;   /* failed status border */
    --run-line:#a9c7ea;   /* job in progress */
    --run-bg:#f0f6fc;
    --tag-ext-line:#d4b75c;   /* 'external' tag border */
    --tag-legacy-line:#c4a7e7;   /* 'legacy' tag border */
    --period-line:#aacbf0;   /* active period tag border */
    --row-hover:#f7f8fc;   /* table row hover */
    --row-alt:#f4f5f7;   /* grouped table, even first cell */
    --row-alt-hover:#e9f2fc;
    --tooltip-bg:#1f2328;   /* tooltip and log surfaces — dark, so text on it is --on-solid */
    --chat-tool-bg:#f6f8fa;   /* tool-call block in the chat log */
    --option-fg:#111111;   /* native <option> text, which ignores most inherited colour */
    /* radius */
    --r-xs:4px;   /* legend swatch, thin bar */
    --r-sm:6px;   /* inline code, small chip. WAS 12px until 2026-08-03 — every var(--r-sm) was remapped to --r-lg in the same commit. */
    --r-md:8px;   /* button, input, select */
    --r-lg:12px;   /* inner card, panel */
    --r-xl:16px;   /* card. Was --r. */
    --r-pill:999px;   /* fully-rounded chip, badge, tag */
    /* shadow */
    --sh:0 1px 2px rgba(16,24,40,.04),0 1px 3px rgba(16,24,40,.06);   /* resting card / button */
    --sh-lift:0 10px 30px rgba(16,24,40,.10);   /* hover / floating */
  }
"""

# Copied verbatim from frontend/src/styles/base-elements.css.
ELEMENTS_CSS = """
  /* The element base — html/body reset, headings, buttons, form controls, code.
     THE one copy. Both render paths get exactly this text:
       - the React path imports it from base.css (Vite inlines it)
       - the Python path gets it as tokens.ELEMENTS_CSS, which tools/gen_tokens.py
         copies out of this file into backend/tokens.py
     It used to live twice, hand-copied, and the copies had to be reconciled by eye.
     Do not add @font-face here: that is the ONE rule the two paths must NOT share
     (block on React, swap on Python — see base.css for why). */

    /* Always reserve the vertical scrollbar so navigating between short pages (no
       scrollbar) and tall ones (scrollbar) doesn't shift the layout — the sidebar
       was visibly "jumping" horizontally by the scrollbar width on each route
       change (each React route is a full page load). No-op where scrollbars are
       overlay (macOS trackpad) or where the page already scrolls. */
    html{overflow-y:scroll}
    /* margin:0 belongs here, not per page: most pages reset it in their own CSS but
       /identity and /views never did (their legacy templates didn't either), so the
       browser's default 8px shifted the WHOLE page — sidebar included — right and
       down on those routes. Shared = both the React shell and the legacy pages get
       the reset, so pixel-parity holds while the routes stop disagreeing. */
    body{margin:0;background:var(--bg);color:var(--ink);
      font-family:'Jakarta','Inter',-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
      -webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}
    h1,h2,h3{letter-spacing:-.02em}
    h1{font-weight:800} h2,h3{font-weight:700}
    .num{font-variant-numeric:tabular-nums;letter-spacing:-.02em}
    a{color:var(--acc-ink)}
    /* Buttons — pill-ish, Jakarta, indigo primary. Matches the report chrome. */
    button,.btn,a.btn,input[type=submit]{border:1px solid var(--line2);background:var(--panel);
      color:var(--ink);border-radius:var(--r-md);padding:8px 14px;font:600 13.5px/1.4 inherit;cursor:pointer;
      box-shadow:var(--sh);transition:border-color .12s,background .12s,box-shadow .12s}
    button:hover,.btn:hover,a.btn:hover{border-color:var(--line2);box-shadow:var(--sh-lift)}
    button.primary,.btn.primary,a.btn.primary,input[type=submit]{background:var(--acc);
      border-color:var(--acc);color:var(--on-solid);box-shadow:0 4px 12px rgba(91,91,240,.28)}
    button.primary:hover,.btn.primary:hover{background:var(--acc-ink);border-color:var(--acc-ink)}
    button:disabled,.btn:disabled{opacity:.5;cursor:default;box-shadow:none}
    /* Form controls */
    input,select,textarea{border:1px solid var(--line2);border-radius:var(--r-md);padding:8px 11px;
      font:inherit;font-size:14px;background:var(--panel);color:var(--ink)}
    input:focus,select:focus,textarea:focus{outline:none;border-color:var(--acc);
      box-shadow:0 0 0 3px rgba(91,91,240,.14)}
    code{background:var(--panel2);padding:1px 5px;border-radius:var(--r-sm);font-size:12.5px}
"""

# Colour VALUES for server-side code. The backend emits colours inside API payloads (a
# chart series' `color`, an element default, a score band), which a CSS custom
# property cannot reach — so those sites read from here rather than carrying their own
# literals.
VALUES = {
    "bg": "#f5f6f9",
    "panel": "#ffffff",
    "panel2": "#eef1f5",
    "line": "#eceef2",
    "line2": "#e2e6ec",
    "ink": "#101828",
    "ink2": "#475467",
    "mut": "#656e80",
    "acc": "#5b5bf0",
    "acc-ink": "#4a45d6",
    "on-solid": "#ffffff",
    "good": "#0c7f47",
    "good-bg": "#e7f6ee",
    "warn": "#a26b1b",
    "bad": "#d41e24",
    "bad-bg": "#fdeaea",
    "bad-soft": "#fff5f5",
    "acc-soft": "#edecfe",
    "acc-bg": "#eeeefe",
    "warn-bg": "#fbf3e2",
    "dup": "#5b5bf0",
    "star": "#f5a623",
    "violet": "#8b5cf6",
    "violet-bg": "#f0ebfe",
    "code-bg": "#0d1117",
    "code-fg": "#c9d1d9",
    "chg-design": "#8250df",
    "chg-design-bg": "rgba(130,80,223,.14)",
    "swatch-empty": "#888888",
    "company-empty": "#8b949e",
    "plat": "#5b5bf0",
    "app": "#8b5cf6",
    "c-commit": "#5b5bf0",
    "c-loc": "#8b5cf6",
    "c-pr": "#2f80ed",
    "c-spec": "#f59e0b",
    "c-bug": "#ef4444",
    "c-epic": "#8b5cf6",
    "c-story": "#10b981",
    "c-feature": "#10b981",
    "c-people": "#06b6d4",
    "c-other": "#9aa3b2",
    "cat-bug": "#ef4444",
    "cat-feature": "#10b981",
    "cat-task": "#8b5cf6",
    "cat-epic": "#5b5bf0",
    "cat-spec": "#f59e0b",
    "cat-docs": "#06b6d4",
    "cat-test": "#2f80ed",
    "cat-other": "#9aa3b2",
    "pill-good-bg": "#dafbe1",
    "pill-good-fg": "#116329",
    "pill-attn-bg": "#fff8c5",
    "pill-attn-fg": "#7d4e00",
    "pill-bad-bg": "#ffebe9",
    "pill-bad-fg": "#cf222e",
    "exact-bg": "#eafff0",
    "exact-fg": "#1a7f37",
    "heur-bg": "#fff8e6",
    "heur-fg": "#9a6700",
    "exp-bg": "#f59e0b22",
    "exp-line": "#f59e0b55",
    "exp-fg": "#9a5c00",
    "good-line": "#a0d8b0",
    "warn-line": "#e8d8a0",
    "bad-line": "#e6a0a0",
    "run-line": "#a9c7ea",
    "run-bg": "#f0f6fc",
    "tag-ext-line": "#d4b75c",
    "tag-legacy-line": "#c4a7e7",
    "period-line": "#aacbf0",
    "row-hover": "#f7f8fc",
    "row-alt": "#f4f5f7",
    "row-alt-hover": "#e9f2fc",
    "tooltip-bg": "#1f2328",
    "chat-tool-bg": "#f6f8fa",
    "option-fg": "#111111",
    "score-good": "#10b981",
    "score-mid": "#f59e0b",
    "score-bad": "#ef4444",
    "r-xs": "4px",
    "r-sm": "6px",
    "r-md": "8px",
    "r-lg": "12px",
    "r-xl": "16px",
    "r-pill": "999px",
    "sh": "0 1px 2px rgba(16,24,40,.04),0 1px 3px rgba(16,24,40,.06)",
    "sh-lift": "0 10px 30px rgba(16,24,40,.10)",
}

CATEGORY_SWATCHES = [
    "#5b5bf0",
    "#8b5cf6",
    "#f59e0b",
    "#06b6d4",
    "#10b981",
    "#ef4444",
    "#2f80ed",
    "#d946ef",
]

# Company series colours, assigned by a name-derived hash (store.company_color_map) so
# a company keeps its colour as ranks change. The teal was #0a7ea4, which sat 58 units
# from the blue in RGB — close enough that two adjacent series read as one colour;
# #14b8a6 is 95 from its nearest neighbour.
COMPANY_PALETTE = [
    "#0969da",
    "#8250df",
    "#1a7f37",
    "#bf8700",
    "#cf222e",
    "#14b8a6",
    "#d946ef",
    "#6e7781",
]

PILLAR_COLORS = {
    "engagement": "#5b5bf0",
    "delivery": "#06b6d4",
    "craft": "#10b981",
    "flow": "#f59e0b",
}

BAND_COLORS = {
    "Strong": "#10b981",
    "Solid": "#2f80ed",
    "Developing": "#f59e0b",
    "Building": "#ef4444",
}

WORKTYPE_COLORS = {
    "feat": "#5b5bf0",
    "fix": "#ef4444",
    "docs": "#06b6d4",
    "test": "#10b981",
    "refactor": "#8b5cf6",
    "chore": "#9aa3b2",
    "perf": "#f59e0b",
    "build": "#2f80ed",
    "ci": "#d946ef",
    "style": "#a3a3a3",
    "revert": "#e11d48",
    "other": "#9aa3b2",
}

FLOW_STAGE_COLORS = {
    "backlog": "#9aa3b2",
    "ready": "#06b6d4",
    "in_progress": "#8b5cf6",
    "review": "#f59e0b",
    "qa": "#2f80ed",
    "done": "#10b981",
    "released": "#5b5bf0",
}

ELEMENT_DEFAULTS = {
    "platform": "#5b5bf0",
    "app": "#8b5cf6",
}

# One-off named series in specific charts. The frontend legend swatches in Trend.tsx
# mirror `opened`/`merged`, so both sides now read the same entry instead of two
# hand-matched literals.
SERIES_COLORS = {
    "total": "#1f2328",
    "opened": "#2f80ed",
    "merged": "#10b981",
    "ttm": "#f59e0b",
    "contributors": "#8b5cf6",
    "commits": "#5b5bf0",
    "specs": "#8b5cf6",
    "prs": "#2f80ed",
    "issues": "#f59e0b",
    "rework": "#f59e0b",
    "first_pass": "#2f80ed",
}
