#!/usr/bin/env python3
"""Generate the visual-token artefacts from design/tokens.json.

    python3 tools/gen_tokens.py            # write the artefacts
    python3 tools/gen_tokens.py --check    # exit 1 if they are stale (what CI asks)

Why a generator rather than one CSS file both paths read: the portal renders through
two paths and the token block used to exist twice, copied by hand — once in
frontend/src/styles/base.css for the React path, once in backend/shell.py's BASE_CSS
for the Python path. The comment at the top of base.css warned about it. This makes
the duplication mechanical.

The @font-face rules deliberately stay OUT of here and remain per-path: the React
copy uses font-display:block and the Python copy uses swap, which is the one
divergence between the two that is intentional (see base.css). Only the `:root` block
is shared, so the generator cannot flatten a difference that is load-bearing.

Emitting Python rather than having shell.py read the CSS off disk keeps the backend
free of a runtime file read and a path lookup, and keeps `import shell` working in a
tree where the frontend has not been built.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "design" / "tokens.json"
STYLES = ROOT / "frontend" / "src" / "styles"
CSS_OUT = STYLES / "tokens.css"
ELEMENTS_SRC = STYLES / "base-elements.css"
PY_OUT = ROOT / "backend" / "tokens.py"
TS_OUT = ROOT / "frontend" / "src" / "lib" / "tokens.ts"

BANNER = "GENERATED by tools/gen_tokens.py from design/tokens.json — do not edit."

# The order groups appear in the emitted block. Explicit rather than derived from the
# JSON so a reordered source file cannot silently reshuffle the output and show up as
# a diff in every review.
GROUPS = ("color", "chart", "category", "status", "score", "radius", "shadow")

# `score` is read from TS only (PersonScore picks a band in JS), so emitting it as CSS
# would be dead weight in every page's <style>. It still lives in the same source
# because it is the same design decision.
CSS_GROUPS = ("color", "chart", "category", "status", "radius", "shadow")


def load() -> dict:
    return json.loads(SOURCE.read_text())


def entries(theme: dict, group: str) -> dict:
    """A group's real tokens — `_note` keys are documentation for the reader of the
    JSON, not tokens, so they never reach an artefact."""
    return {k: v for k, v in theme.get(group, {}).items() if not k.startswith("_")}


def flat_values(data: dict) -> dict:
    """Every token as name -> value, across all groups. What server-side code needs:
    a colour that goes into an API payload cannot be a CSS custom property."""
    theme = data["themes"]["light"]
    return {name: spec["value"]
            for group in GROUPS
            for name, spec in entries(theme, group).items()}


def palettes(data: dict):
    """Yields (name, note, value) for each palette, normalising the three shapes the
    source file uses: a bare list, a `{_note, values}` wrapper around a list, and a
    plain mapping (whose own `_note` is pulled out)."""
    for name, spec in data.get("palettes", {}).items():
        if name.startswith("_"):
            continue
        if isinstance(spec, list):
            yield name, None, spec
        elif "values" in spec:
            yield name, spec.get("_note"), spec["values"]
        else:
            yield name, spec.get("_note"), {k: v for k, v in spec.items()
                                            if not k.startswith("_")}


def root_block(theme: dict, selector: str = ":root") -> str:
    """One `:root{...}` block. Values are emitted verbatim — the point of the source
    file is that it holds exactly what ships, with no arithmetic in between."""
    lines = [f"{selector}{{"]
    for group in CSS_GROUPS:
        group_entries = entries(theme, group)
        if not group_entries:
            continue
        lines.append(f"  /* {group} */")
        for name, spec in group_entries.items():
            note = spec.get("note")
            suffix = f"   /* {note} */" if note else ""
            lines.append(f"  --{name}:{spec['value']};{suffix}")
    lines.append("}")
    return "\n".join(lines)


def themed_css(data: dict) -> str:
    """Light in `:root`, dark as an override in three places.

    The dark block lists only what DIFFERS, so anything absent inherits the light value
    through the cascade — that is why chart/*, category/*, score/* and radius/* need no
    dark entries at all.

    Three selectors, in this order, because each answers a different question:
      * the media query is the default — respect the OS without any JS having run;
      * `:not([data-theme="light"])` lets an explicit light choice win over a dark OS;
      * `[data-theme="dark"]` lets an explicit dark choice win over a light OS.
    `color-scheme` comes along so native scrollbars, form controls and the caret follow
    the theme; without it a dark page keeps white scrollbars."""
    themes = data["themes"]
    out = [root_block(themes["light"]).replace("{", "{\n  color-scheme:light;", 1)]
    dark = themes.get("dark")
    if dark:
        body = root_block(dark, ':root[data-theme="dark"]')
        media = root_block(dark, ':root:not([data-theme="light"])')
        out += [
            "",
            "/* The OS preference, honoured before any JS runs. */",
            "@media (prefers-color-scheme:dark){",
            "\n".join("  " + ln for ln in media.replace("{", "{\n  color-scheme:dark;", 1).splitlines()),
            "}",
            "",
            "/* An explicit choice, which must beat the OS in either direction. */",
            body.replace("{", "{\n  color-scheme:dark;", 1),
        ]
    return "\n".join(out)


def render_css(data: dict) -> str:
    return f"/* {BANNER} */\n" + themed_css(data) + "\n"


def _indent(css: str) -> str:
    """Two spaces, matching the hand-written CSS already inside shell.py's strings —
    the emitted constants land in the same <style> block as SHELL_CSS/CHART_CSS."""
    return "\n".join(f"  {line}" if line.strip() else line for line in css.splitlines())


def _py_literal(name: str, css: str, doc: str) -> str:
    if '"""' in css or css.rstrip().endswith("\\"):
        raise SystemExit(f"{name}: CSS cannot contain a triple quote or a trailing backslash")
    return f'# {doc}\n{name} = """\n{_indent(css.strip())}\n"""\n'


def render_py(data: dict) -> str:
    """The Python path's copy of both shared pieces, as two string constants that
    shell.py concatenates into BASE_CSS."""
    # themed_css, NOT one root_block per theme: emitting the dark block as a bare
    # `:root` would make it unconditional, so every server-rendered page would be dark
    # regardless of the OS or the user's choice. The test that caught this is
    # ParityTest.test_both_paths_apply_the_same_rules_apart_from_the_fonts.
    tokens = themed_css(data)
    elements = ELEMENTS_SRC.read_text()
    return (
        f'"""{BANNER}\n\n'
        "The two pieces of the visual base that BOTH render paths share, carried over to\n"
        "the Python side so nothing is hand-copied:\n\n"
        "  TOKENS_CSS   — the `:root` block, from design/tokens.json\n"
        "  ELEMENTS_CSS — the element base, from frontend/src/styles/base-elements.css\n\n"
        "The React path gets the same two via frontend/src/styles/base.css. @font-face is\n"
        "deliberately absent from both: that is the one rule the paths must not share\n"
        "(font-display block vs swap). See docs/design-system.md.\n"
        '"""\n\n'
        + _py_literal("TOKENS_CSS", tokens,
                      "Generated from design/tokens.json.")
        + "\n"
        + _py_literal("ELEMENTS_CSS", elements,
                      "Copied verbatim from frontend/src/styles/base-elements.css.")
        + "\n"
        + _py_values(data)
    )


def _wrap(text: str, width: int = 86, prefix: str = "# ") -> str:
    words, lines, cur = text.split(), [], prefix.rstrip()
    for w in words:
        if len(cur) + len(w) + 1 > width and cur.strip() != prefix.strip():
            lines.append(cur)
            cur = prefix + w
        else:
            cur = f"{cur} {w}" if cur.strip() not in ("", "#") else prefix + w
    lines.append(cur)
    return "\n".join(lines)


def _py_values(data: dict) -> str:
    """Colour VALUES and the palettes, for server-side code.

    The backend puts colours into API payloads — a chart series' `color`, an element's
    default, a score band — so it needs values, not custom properties. These used to be
    literals spread across render.py, store.py, collect.py and semantic_metrics.py,
    including three separate copies of the same eight-colour swatch list."""
    out = [
        _wrap("Colour VALUES for server-side code. The backend emits colours inside API "
              "payloads (a chart series' `color`, an element default, a score band), which "
              "a CSS custom property cannot reach — so those sites read from here rather "
              "than carrying their own literals."),
        "VALUES = {",
    ]
    out += [f'    "{name}": "{value}",' for name, value in flat_values(data).items()]
    out += ["}", ""]
    for name, note, value in palettes(data):
        const = name.upper()
        if note:
            out.append(_wrap(note))
        if isinstance(value, list):
            out.append(f"{const} = [")
            out += [f'    "{v}",' for v in value]
            out += ["]", ""]
        else:
            out.append(f"{const} = {{")
            out += [f'    "{k}": "{v}",' for k, v in value.items()]
            out += ["}", ""]
    return "\n".join(out)


def render_ts(data: dict) -> str:
    """Colours that have to reach JavaScript.

    A CSS custom property cannot be read from a recharts prop, an inline style, or a
    `return "#10b981"` in a score helper, so those sites used to carry their own hex
    literals — a second palette that drifted from the CSS one by construction. This
    module is that palette, from the same source.

    Prefer `var(--x)` in CSS. Import from here only where JS genuinely needs a value."""
    theme = data["themes"]["light"]
    flat = {name: spec["value"]
            for group in GROUPS
            for name, spec in entries(theme, group).items()}
    lines = [
        f"// {BANNER}",
        "//",
        "// Colours that must reach JS — recharts props, inline styles, score bands.",
        "// In CSS use var(--token) instead; these exist because a custom property",
        "// cannot be read from a JS expression.",
        "",
        "export const token = {",
    ]
    lines += [f'  "{name}": "{value}",' for name, value in flat.items()]
    lines += [
        "} as const;",
        "",
        "export type TokenName = keyof typeof token;",
        "",
        "/** A token as a CSS reference, for inline styles: css(\"c-pr\") -> \"var(--c-pr)\". */",
        "export function css(name: TokenName): string {",
        "  return `var(--${name})`;",
        "}",
        "",
    ]
    top_note = data.get("palettes", {}).get("_note")
    if top_note:
        lines += [f"// {top_note}", ""]
    for pal_name, note, values in palettes(data):
        const = pal_name.upper()
        if note:
            lines.append(f"// {note}")
        if isinstance(values, list):
            lines.append(f"export const {const}: readonly string[] = [")
            lines += [f'  "{v}",' for v in values]
            lines += ["];", ""]
        else:
            lines.append(f"export const {const}: Readonly<Record<string, string>> = {{")
            lines += [f'  {k}: "{v}",' for k, v in values.items()]
            lines += ["};", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if any artefact is stale")
    args = ap.parse_args(argv)

    data = load()
    wanted = {CSS_OUT: render_css(data), PY_OUT: render_py(data),
              TS_OUT: render_ts(data)}

    if args.check:
        stale = [p for p, text in wanted.items()
                 if not p.exists() or p.read_text() != text]
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)}", file=sys.stderr)
        if stale:
            print("run: python3 tools/gen_tokens.py", file=sys.stderr)
            return 1
        return 0

    for p, text in wanted.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
