// GENERATED by tools/gen_tokens.py from design/tokens.json — do not edit.
//
// Colours that must reach JS — recharts props, inline styles, score bands.
// In CSS use var(--token) instead; these exist because a custom property
// cannot be read from a JS expression.

export const token = {
  "bg": "#f5f6f9",
  "panel": "#ffffff",
  "panel2": "#eef1f5",
  "line": "#eceef2",
  "line2": "#e2e6ec",
  "ink": "#101828",
  "ink2": "#475467",
  "mut": "#8a93a3",
  "acc": "#5b5bf0",
  "acc-ink": "#4a45d6",
  "on-solid": "#ffffff",
  "good": "#0f9d58",
  "good-bg": "#e7f6ee",
  "warn": "#b7791f",
  "bad": "#e5484d",
  "bad-bg": "#fdeaea",
  "bad-soft": "#fff5f5",
  "acc-soft": "#edecfe",
  "acc-bg": "#eeeefe",
  "warn-bg": "#fbf3e2",
  "dup": "#5b5bf0",
  "star": "#f5a623",
  "violet": "#8b5cf6",
  "violet-bg": "#f0ebfe",
  "code-bg": "#0d1117",
  "code-fg": "#c9d1d9",
  "chg-design": "#8250df",
  "chg-design-bg": "rgba(130,80,223,.14)",
  "swatch-empty": "#888888",
  "company-empty": "#8b949e",
  "plat": "#5b5bf0",
  "app": "#8b5cf6",
  "c-commit": "#5b5bf0",
  "c-loc": "#8b5cf6",
  "c-pr": "#2f80ed",
  "c-spec": "#f59e0b",
  "c-bug": "#ef4444",
  "c-epic": "#8b5cf6",
  "c-story": "#10b981",
  "c-feature": "#10b981",
  "c-people": "#06b6d4",
  "c-other": "#9aa3b2",
  "cat-bug": "#ef4444",
  "cat-feature": "#10b981",
  "cat-task": "#8b5cf6",
  "cat-epic": "#5b5bf0",
  "cat-spec": "#f59e0b",
  "cat-docs": "#06b6d4",
  "cat-test": "#2f80ed",
  "cat-other": "#9aa3b2",
  "pill-good-bg": "#dafbe1",
  "pill-good-fg": "#116329",
  "pill-attn-bg": "#fff8c5",
  "pill-attn-fg": "#7d4e00",
  "pill-bad-bg": "#ffebe9",
  "pill-bad-fg": "#cf222e",
  "exact-bg": "#eafff0",
  "exact-fg": "#1a7f37",
  "heur-bg": "#fff8e6",
  "heur-fg": "#9a6700",
  "exp-bg": "#f59e0b22",
  "exp-line": "#f59e0b55",
  "exp-fg": "#c77700",
  "good-line": "#a0d8b0",
  "warn-line": "#e8d8a0",
  "bad-line": "#e6a0a0",
  "run-line": "#a9c7ea",
  "run-bg": "#f0f6fc",
  "tag-ext-line": "#d4b75c",
  "tag-legacy-line": "#c4a7e7",
  "period-line": "#aacbf0",
  "row-hover": "#f7f8fc",
  "row-alt": "#f4f5f7",
  "row-alt-hover": "#e9f2fc",
  "tooltip-bg": "#1f2328",
  "chat-tool-bg": "#f6f8fa",
  "option-fg": "#111111",
  "score-good": "#10b981",
  "score-mid": "#f59e0b",
  "score-bad": "#ef4444",
  "r": "16px",
  "r-sm": "12px",
  "sh": "0 1px 2px rgba(16,24,40,.04),0 1px 3px rgba(16,24,40,.06)",
  "sh-lift": "0 10px 30px rgba(16,24,40,.10)",
} as const;

export type TokenName = keyof typeof token;

/** A token as a CSS reference, for inline styles: css("c-pr") -> "var(--c-pr)". */
export function css(name: TokenName): string {
  return `var(--${name})`;
}

// Colours handed out in code rather than referenced from CSS. A list's ORDER is load-bearing — it decides which colour a work type gets by index, so appending is safe and reordering repaints existing types. Several of these also exist in backend/render.py (_ELEM_PALETTE, _PILLAR_COLORS, _WORKTYPE_COLORS, _BAND_COLORS); the backend does not read this file yet, so those remain a hand-kept twin — see docs/design-system.md.

export const CATEGORY_SWATCHES: readonly string[] = [
  "#5b5bf0",
  "#8b5cf6",
  "#f59e0b",
  "#06b6d4",
  "#10b981",
  "#ef4444",
  "#2f80ed",
  "#d946ef",
];

export const PILLAR_COLORS: Readonly<Record<string, string>> = {
  engagement: "#5b5bf0",
  delivery: "#06b6d4",
  craft: "#10b981",
  flow: "#f59e0b",
};
